"""empty message

Revision ID: 177119cd9b47
Revises: ae1580540d53
Create Date: 2020-10-26 01:05:22.750155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177119cd9b47'
down_revision = 'ae1580540d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'posted')
    # ### end Alembic commands ###
